project_id = "ghmpaghyasyllfvamfna"
[functions.send-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-email/*.html" ]

[functions.send-invitation-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-invitation-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-invitation-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-invitation-email/*.html" ]

[functions.razorpay-payment]
enabled = true
verify_jwt = false
import_map = "./functions/razorpay-payment/deno.json"
entrypoint = "./functions/razorpay-payment/index.ts"

[functions.payment-engine]
enabled = true
verify_jwt = false
import_map = "./functions/payment-engine/deno.json"
entrypoint = "./functions/payment-engine/index.ts"
